#
# M5NR configuration file
#
# supported variables:
#
# M5NR_VERSION   Version of this build of M5NR
# M5NR_BIN       Full path to the "bin" directory in the myM5NR repository
# PARSED_DIR     Full path to the directory containing parsed source data
# SOURCE_FILE    Full path to sources.yaml file in the myM5NR repository
#
#####

# id2func.txt
- name: Functions
  rank: 1
  parser:
    - cat ${PARSED_DIR}/*/md52func.sort.txt ${PARSED_DIR}/*/id2func.txt | cut -f2 | sort -T . -u -o unique_func.txt
    - COUNT=0; while read FUNC; do ((COUNT++)); echo "${COUNT}"$'\t'"${FUNC}"; done < unique_func.txt > id2func.txt

# md52lca.txt
- name: LCA
  rank: 1
  parser:
    - sort -T . -m -u -o md52taxid.all.txt ${PARSED_DIR}/*/md52taxid.sort.txt
    - ${M5NR_BIN}/md52lca.py --taxa ${PARSED_DIR}/NCBI-Taxonomy/taxonomy.json --input md52taxid.all.txt --output md52lca.txt

# taxonomy.json.gz / functional.json.gz
- name: Hierarchies
  rank: 1
  parser:
    - ${M5NR_BIN}/hierarchy2tree.py --type taxonomy --input ${PARSED_DIR}/NCBI-Taxonomy/taxonomy.tsv --output taxonomy.json
    - ${M5NR_BIN}/hierarchy2tree.py --type functional --input ${SOURCE_FILE} --output functional.json --parsedir ${PARSED_DIR}
    - gzip taxonomy.json
    - gzip functional.json

# m5nr.fasta
- name: M5nr
  rank: 1
  parser:
    - sort -T . -m -u ${PARSED_DIR}/*/md52seq.sort.txt | ${M5NR_BIN}/tab2fasta.pl > m5nr.raw.fasta
    - ${M5NR_BIN}/seq_length_stats.py --input m5nr.raw.fasta --output m5nr.raw.stats --protein --strict --iupac --x_percent 85
    - ${M5NR_BIN}/seqUtil --input m5nr.raw.fasta --output m5nr.fasta --stdfasta --protein --iupac --ambig_trim --dna_trim --per_trim 85 --minimum 20
    - ${M5NR_BIN}/seq_length_stats.py --input m5nr.fasta --output m5nr.stats --protein --strict --iupac --x_percent 85
    - diamond makedb --in m5nr.fasta -d m5nr

# m5rna.fasta
- name: M5rna
  rank: 1
  parser:
    - sort -T . -m -u ${PARSED_DIR}/*/md52rnaseq.sort.txt | ${M5NR_BIN}/tab2fasta.pl > m5rna.raw.fasta
    - ${M5NR_BIN}/seq_length_stats.py --input m5rna.fasta --output m5rna.stats --strict
    - diamond makedb --in m5rna.fasta -d m5rna
    - vsearch --quiet --strand both --id 0.8 --cluster_fast m5rna.fasta --centroids m5rna.clust.fasta
    - ${M5NR_BIN}/seq_length_stats.py --input m5rna.clust.fasta --output m5rna.clust.stats --strict
    - mkdir -p index
    - indexdb_rna --ref m5rna.clust.fasta,index/m5rna.clust.index

# m5nr_v#.ldb
- name: LevelDB
  rank: 2
  depends:
    - Functions
    - LCA
  parser:
    - mkdir -p m5nr.ldb
    - ${M5NR_BIN}/merge_annotation.py --parsedir ${PARSED_DIR} --taxa ${PARSED_DIR}/NCBI-Taxonomy/taxonomy.json --lca ../LCA/md52lca.txt --func ../Functions/id2func.txt --sources ${SOURCE_FILE} --db m5nr_v${M5NR_VERSION}.ldb
    - tar -zcf m5nr_v${M5NR_VERSION}.ldb.tgz m5nr_v${M5NR_VERSION}.ldb

# m5nr_v#.bdb
- name: BerkelyDB
  rank: 3
  depends:
    - LevelDB
  parser:
    - ${M5NR_BIN}/export_annotation_for_bdb.py --sources ${SOURCE_FILE} --db ../LevelDB/m5nr.ldb --output m5nr_v${M5NR_VERSION}.bdb
    - gzip m5nr_v${M5NR_VERSION}.bdb

- name: Cassandra
  rank: 3
  depends:
    - LevelDB
  parser:
    - ${M5NR_BIN}/export_annotation_for_cass.py --parsedir ${PARSED_DIR} --taxa ${PARSED_DIR}/NCBI-Taxonomy/taxonomy.tsv --sources ${SOURCE_FILE} --db ../LevelDB/m5nr.ldb --output m5nr_v${M5NR_VERSION}
    - tar -zcf m5nr_v${M5NR_VERSION}.cass.tgz m5nr_v${M5NR_VERSION}.*

- name: Solr
  rank: 3
  depends:
    - LevelDB
  parser:
    - ${M5NR_BIN}/export_annotation_for_solr.py --parsedir ${PARSED_DIR} --taxa ${PARSED_DIR}/NCBI-Taxonomy/taxonomy.tsv --sources ${SOURCE_FILE} --db ../LevelDB/m5nr.ldb --output m5nr_v${M5NR_VERSION}
    - tar -zcf m5nr_v${M5NR_VERSION}.solr.tgz m5nr_v${M5NR_VERSION}.*

