#
# M5NR configuration file
#
# supported variables:
#
# M5NR_BIN       Full path to the "bin" directory in the myM5NR repository (use in any field)
# SOURCE_DIR     The directory where the source data is located (use "parser" field)
# VERSION        Version string as obtained from remote website (use in "download" field)
# user-defined   Use dict "env" to create user defined environvent variables: key is name of new variable, value is a command that generate value
#
# fields:
#   download: [<url>] uses curl by default. For wget and scripts specify an explicit command in field "download-command".
#   download-command: <command> or [<command>]
#   parser: <command> or [<command>]

#
# SORT ALPHABETICALLY
#
##### protein

BacMet:
    category: protein
    homepage: http://bacmet.biomedicine.gu.se/
    type: Functional annotation
    version: curl --silent "http://bacmet.biomedicine.gu.se/index.html" | grep -o  "Database Statistics (version [0-9\.]*)" | grep -o [0-9\.]*
    download: http://bacmet.biomedicine.gu.se/download/BacMet1.1.zip
    parser:
      - unzip ${SOURCE_DIR}/BacMet1.1.zip -d ${SOURCE_DIR}
      - ${M5NR_BIN}/bacmet.pl ${SOURCE_DIR}/BacMet_EXP.704.fasta ${SOURCE_DIR}/BacMet_PRE.*.fasta

CARD:
    category: protein
    homepage: https://card.mcmaster.ca
    type: Functional annotation
    version: curl --silent "https://card.mcmaster.ca/download" | grep ">CARD<" | grep -o ">[0-9][0-9\.]*<" | head -n1 |  grep -o "[0-9\.]*"
    download: https://card.mcmaster.ca/latest/data
    parser:
      - tar -xjf ${SOURCE_DIR}/data -C ${SOURCE_DIR}
      # note, file name 'ncbi_taxomony.csv' is misspelled in tarball, may have name changed in future
      - ${M5NR_BIN}/card.pl ${SOURCE_DIR}/protein_fasta_protein_homolog_model.fasta ${SOURCE_DIR}/ncbi_taxomony.csv
      - ${M5NR_BIN}/obo2hierarchy.pl ${SOURCE_DIR}/aro.obo

CAZy:
    category: protein
    homepage: http://www.cazy.org
    type: Hierarchical functional annotation
    depth: 2
    no-download: true
    depends:
      - TrEmble
      - Swiss-Prot
    parser:
      - cp ../TrEmble/md52id_cazy.txt md52id.txt
      - cat ../Swiss-Prot/md52id_cazy.txt >> md52id.txt
      - ${M5NR_BIN}/create-cazy-hierarchy.pl --input md52id.txt > id2hierarchy.txt
    # the hierarchy is hardcoded in script

COG:
    category: protein
    type: Hierarchical functional annotation
    depth: 3
    version: echo '-'
    depends:
      - Swiss-Prot
      - TrEmble
    download:
      - http://eggnogdb.embl.de/download/eggnog_4.5/data/NOG/NOG.annotations.tsv.gz
    parser:
      - fgrep COG ../TrEmble/md52id_cog.txt > md52id.txt
      - fgrep COG ../Swiss-Prot/md52id_cog.txt >> md52id.txt
      - zcat ${SOURCE_DIR}/NOG.annotations.tsv.gz | cut -f2,5,6 | fgrep COG > id2func.txt
      - ${M5NR_BIN}/create-nog-hierarchy.pl --input id2func.txt > id2hierarchy.txt
    # the hierarchy is hardcoded in script

EC:
    category: protein
    type: Hierarchical functional annotation
    depth: 4
    homepage: https://enzyme.expasy.org
    version: curl -s "ftp://ftp.expasy.org/databases/enzyme/release/enzclass.txt" | grep '^Release' | grep -o '[0-9a-zA-Z\-]\+$'
    download:
      - ftp://ftp.expasy.org/databases/enzyme/enzyme.dat
      - ftp://ftp.expasy.org/databases/enzyme/enzclass.txt
    depends:
      - Swiss-Prot
      - TrEmble
    parser:
      - cp ../TrEmble/md52id_ec.txt md52id.txt
      - cat ../Swiss-Prot/md52id_ec.txt >> md52id.txt
      - ${M5NR_BIN}/create-ec-hierarchy.pl --class ${SOURCE_DIR}/enzclass.txt --input ${SOURCE_DIR}/enzyme.dat > id2hierarchy.txt

EggNOG:
    category: protein
    type: Hierarchical functional annotation
    depth: 3
    homepage: http://eggnogdb.embl.de
    version: curl --silent "http://eggnogdb.embl.de/download/" | grep -o "eggnog_[0-9\.]*" | cut -d "_" -f 2 | sort -u  --version-sort  | tail -n1
    depends:
      - Swiss-Prot
      - TrEmble
    download:
      - http://eggnogdb.embl.de/download/eggnog_4.5/data/NOG/NOG.annotations.tsv.gz
    parser:
      - fgrep ENOG ../TrEmble/md52id_eggnog.txt > md52id.txt
      - fgrep ENOG ../Swiss-Prot/md52id_eggnog.txt >> md52id.txt
      - zcat ${SOURCE_DIR}/NOG.annotations.tsv.gz | cut -f2,5,6 | fgrep ENOG > id2func.txt
      - ${M5NR_BIN}/create-nog-hierarchy.pl --input id2func.txt > id2hierarchy.txt
    # the hierarchy is hardcoded in script

GenBank:
    category: protein
    type: Functional annotation
    download:
      - ftp://ftp.ncbi.nih.gov/blast/db/FASTA/nr.gz
    version: date --date=$(wget -qO- ftp.ncbi.nih.gov/blast/db/FASTA/ | grep ">nr.gz<" | grep -o "[0-9\-]\{10\}") '+%Y-%m-%d'
    parser:
      - ${M5NR_BIN}/genbank.pl ${SOURCE_DIR}/nr.gz

goslim:
    category: protein
    type: Hierarchical functional annotation
    depth: 3
    homepage: http://www.geneontology.org
    version: curl --silent "http://archive.geneontology.org/full/DATESTAMP"
    download:
      - http://www.geneontology.org/ontology/subsets/goslim_metagenomics.obo
    parser:
      - ${M5NR_BIN}/goslim.pl ${SOURCE_DIR}/goslim_metagenomics.obo

Greengenes:
    category: rRNA
    type: SSU
    homepage: http://greengenes.lbl.gov/
    version: date --date="$(curl --silent http://greengenes.lbl.gov/Download/Sequence_Data/Fasta_data_files/ | grep current_GREENGENES_gg16S_unaligned.fasta.gz | grep -o "[0-9][0-9]-.*-[0-9][0-9][0-9][0-9]")" '+%Y-%m-%d'
    download:
      - http://greengenes.lbl.gov/Download/Sequence_Data/Fasta_data_files/current_GREENGENES_gg16S_unaligned.fasta.gz
    parser:
      - ${M5NR_BIN}/greengenes.pl ${SOURCE_DIR}/current_GREENGENES_gg16S_unaligned.fasta.gz

InterPro:
    category: protein
    type: Hierarchical functional annotation
    version: curl --silent ftp://ftp.ebi.ac.uk/pub/databases/interpro/current/release_notes.txt | grep "Release [0-9]" | grep -o "[0-9]*\.[0-9]*"
    download:
      - ftp://ftp.ebi.ac.uk/pub/databases/interpro/${VERSION}/entry.list
      - ftp://ftp.ebi.ac.uk/pub/databases/interpro/${VERSION}/short_names.dat
      - ftp://ftp.ebi.ac.uk/pub/databases/interpro/${VERSION}/interpro2go
    parser:
      - ${M5NR_BIN}/interpro.pl ${SOURCE_DIR}/interpro2go

KEGG:
    category: protein
    type: Hierarchical functional annotation
    homepage: http://www.genome.jp/kegg/
    depth: 4
    no-download: true
    depends:
      - Swiss-Prot
      - TrEmble
    parser:
      - cp ../TrEmble/md52id_kegg.txt md52id.txt
      - cat ../Swiss-Prot/md52id_kegg.txt >> md52id.txt
    comment: kegg EC and KO mappings obtained from UniProt, KEGG maps from KEGG
    comment2: KO hierarchy from ???

#unique_func.txt
M5functions:
    category: output
    type: protein
    no-download: true
    depends:
      - BacMet
      - CARD
      - CAZy
      - COG
      - EC
      - EggNOG
      - GenBank
      - goslim
      - InterPro
      - KEGG
      - PATRIC
      - PFAM
      - PhAnToMe
      - RefSeq
      - SEED-Annotations
      - SEED-Subsystems
#     - singlecopygenes
      - Swiss-Prot
      - TrEmble
    parser:
      - cut -f2 ../*/md52func.txt | sort -u > unique_func.txt

#M5nr.fasta
M5nr:
    category: output
    type: protein
    no-download: true
    depends:
      - BacMet
      - CARD
      - CAZy
      - COG
      - EC
      - EggNOG
      - GenBank
      - goslim
      - InterPro
      - KEGG
      - PATRIC
      - PFAM
      - PhAnToMe
      - RefSeq
      - SEED-Annotations
      - SEED-Subsystems
#     - singlecopygenes
      - Swiss-Prot
      - TrEmble
    parser:
      - cat ../*/md52seq.txt | sort -u | ${M5NR_BIN}/tab2fasta.pl > m5nr.fasta

#M5rna.fasta
M5rna:
    category: output
    type: rRNA
    no-download: true
    depends:
      - SILVA-SSU
      - SILVA-LSU
      - RDP
      - Greengenes
    parser:
      - cat ../*/md52rnaseq.txt | sort -u | ${M5NR_BIN}/tab2fasta.pl > m5rna.fasta

# MOTUDB a set of 40 protein-coding phylogenetic marker genes (MGs) have been identified (Ciccarelli et al SCience 2006)
motuDB:
    category: protein
    type: Filter set
    homepage: http://www.bork.embl.de/software/mOTU/
    version: curl --silent http://vm-lux.embl.de/~kultima/MOCAT/download.html | grep -o "mOTU\.v[0-9\.] " | grep -o "v[0-9\.]" | grep -o "[0-9\.]"
    download:
      - http://vm-lux.embl.de/~kultima/share/mOTU/mOTU.v${VERSION}.padded.tar.gz
    parser:
      - tar -xzf ${SOURCE_DIR}/mOTU.v${VERSION}.padded.tar.gz -C ${SOURCE_DIR}
      - ${M5NR_BIN}/motudb.pl ${SOURCE_DIR}/mOTU.v${VERSION}.padded

NCBI-Taxonomy:
    category: output
    type: Taxonomy
    homepage: https://www.ncbi.nlm.nih.gov/taxonomy
    version: echo ${TODAY}
    download:
      - http://purl.obolibrary.org/obo/ncbitaxon.obo
    parser:
      - echo "no parser yet"

PATRIC:
    category: protein
    type: Functional annotation
    homepage: https://www.patricbrc.org/
    version: wget -qO- ftp://ftp.patricbrc.org/patric2/ | grep current_release | grep -o "20[0-9][0-9] [a-zA-Z]*"
    download-command: ${M5NR_BIN}/download_PATRIC.sh
    parser:
      - ${M5NR_BIN}/patric.pl ${SOURCE_DIR}/

PFAM:
    category: protein
    type: Functional annotation
    no-download: true
      # comes from Uniprot
    depends:
      - Swiss-Prot
      - TrEmble
    parser:
      - cp ../TrEmble/md52id_pfam.txt md52id.txt
      - cat ../Swiss-Prot/md52id_pfam.txt >> md52id.txt

PhAnToMe:
    category: protein
    type: Functional annotation
    homepage: http://www.phantome.org
    env:
        TIMESTAMP: curl --silent http://www.phantome.org/Downloads/proteins/all_sequences/ | grep -o ">phage_proteins_[0-9]*.fasta.gz" | sort | tail -n 1 | grep -o "[0-9]*"
    version: date -d @${TIMESTAMP} +"%Y%m%d"
    download:
      - http://www.phantome.org/Downloads/proteins/all_sequences/phage_proteins_${TIMESTAMP}.fasta.gz
    comment: curl --silent "http://shock.metagenomics.anl.gov/node?query&type=data-library&project=M5NR&data-library-name=M5NR_source_Phantome&version=${VERSION}" | grep -o "[0-f]\{8\}-[0-f]\{4\}-[0-f]\{4\}-[0-f]\{4\}-[0-f]\{12\}"`
    parser:
      - ${M5NR_BIN}/phantome.pl ${SOURCE_DIR}/phage_proteins_${TIMESTAMP}.fasta.gz

RDP:
    category: rRNA
    type: SSU
    homepage: http://rdp.cme.msu.edu
    version: curl --silent 'http://rdp.cme.msu.edu/download/releaseREADME.txt'
    download:
      - http://rdp.cme.msu.edu/download/current_Bacteria_unaligned.gb.gz
      - http://rdp.cme.msu.edu/download/current_Archaea_unaligned.gb.gz
      - http://rdp.cme.msu.edu/download/current_Fungi_unaligned.gb.gz
    parser:
      - ${M5NR_BIN}/rdp.pl ${SOURCE_DIR}/current_Fungi_unaligned.gb.gz ${SOURCE_DIR}/current_Bacteria_unaligned.gb.gz ${SOURCE_DIR}/current_Archaea_unaligned.gb.gz

RefSeq:
    category: protein
    type: Functional annotation
    version: curl --silent ftp://ftp.ncbi.nih.gov/refseq/release/RELEASE_NUMBER
    env:
        COUNT: curl --silent ftp://ftp.ncbi.nih.gov/refseq/release/complete/ | grep -o "complete.nonredundant_protein.*\.faa\.gz" | sort -V | tail -n 1 | grep -o [0-9]*
    download: ftp://ftp.ncbi.nih.gov/refseq/release/complete/complete.nonredundant_protein.{1..${COUNT}}.protein.gpff.gz
    resume-download: true
    parser:
      - ${M5NR_BIN}/refseq.pl ${SOURCE_DIR}

SEED-Annotations:
    category: protein
    type: Functional annotation
    homepage: http://www.theseed.org
    version: echo ${TODAY}
    download-command: ${M5NR_BIN}/querySAS.pl --source=SEED  --output=SEED.md52id2func2org
    resume-download: true
    parser:
      - ${M5NR_BIN}/seed-annotations.pl ${SOURCE_DIR}/SEED.md52id2func2org

SEED-Subsystems:
    category: protein
    type: Hierarchical functional annotation
    depth: 4
    homepage: http://www.theseed.org
    version: echo ${TODAY}
    download-command: ${M5NR_BIN}/querySAS.pl --source=Subsystems --output=Subsystems.subsystem2role2seq --verbose
    resume-download: true
    parser:
      - ${M5NR_BIN}/subsystems.pl ${SOURCE_DIR}

# no suitable download mechanism other than manual, does not seem to be updated
#FOAM:
#  category: protein
#  homepage: http://cbb.pnnl.gov/portal/software/FOAM.html
#  type: Hierarchical functional annotation
#  download:
#    - http://cbb.pnnl.gov/portal/software/FOAM.html

# not enabeled for now
#singlecopygenes:
#    category: protein
#    type: Filter set
#    comment: From Will

SILVA-LSU:
    category: rRNA
    type: LSU
    homepage: http://www.arb-silva.de
    version: curl --silent -N "ftp://ftp.arb-silva.de//current/Exports/README.txt" | head -n 1 | grep -o "SILVA [0-9.]*" | cut -d ' ' -f 2
    download:
      - ftp://ftp.arb-silva.de/current/Exports/README.txt
      - ftp://ftp.arb-silva.de/current/Exports/SILVA_${VERSION}_LSURef_tax_silva_trunc.fasta.gz
      - ftp://ftp.arb-silva.de/current/Exports/SILVA_${VERSION}_LSURef_tax_silva_trunc.fasta.gz.md5
      - ftp://ftp.arb-silva.de/current/Exports/rast/SILVA_${VERSION}_LSURef.rast.gz
      - ftp://ftp.arb-silva.de/current/Exports/rast/SILVA_${VERSION}_LSURef.rast.gz.md5
    parser:
      - ${M5NR_BIN}/silva.pl ${SOURCE_DIR}/SILVA_${VERSION}_LSURef_tax_silva_trunc.fasta.gz

SILVA-SSU:
    category: rRNA
    type: SSU
    homepage: http://www.arb-silva.de
    version: curl --silent -N "ftp://ftp.arb-silva.de//current/Exports/README.txt" | head -n 1 | grep -o "SILVA [0-9.]*" | cut -d ' ' -f 2
    download:
      - ftp://ftp.arb-silva.de/current/Exports/SILVA_${VERSION}_SSURef_tax_silva_trunc.fasta.gz
      - ftp://ftp.arb-silva.de/current/Exports/SILVA_${VERSION}_SSURef_tax_silva_trunc.fasta.gz.md5
    parser:
      - ${M5NR_BIN}/silva.pl ${SOURCE_DIR}/SILVA_${VERSION}_SSURef_tax_silva_trunc.fasta.gz

Swiss-Prot:
    category: protein
    type: Functional annotation
    download:
      - ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.dat.gz
    version: curl --silent ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/reldate.txt | grep "Swiss-Prot" | grep -o "Release 20[0-9_]*" | grep -o "20[0-9_]*"
    parser:
      - ${M5NR_BIN}/swissprot.pl ${SOURCE_DIR}/uniprot_sprot.dat.gz

TrEmble:
    category: protein
    type: Functional annotation
    download:
      - ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_trembl.dat.gz
    version: curl --silent ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/reldate.txt | grep "TrEMBL" | grep -o "Release 20[0-9_]*" | grep -o "20[0-9_]*"
    parser:
      - ${M5NR_BIN}/trembl.pl ${SOURCE_DIR}/uniprot_trembl.dat.gz
