#
# M5NR configuration file
#
# supported variables:
#
# M5NR_BIN       Full path to the "bin" directory in the myM5NR repository (use in any field)
# SOURCE_DIR     The directory where the source data is located (use "parser" field)
# VERSION        Version string as obtained from remote website (use in "download" field)
# CURL_OPTS      --silent --connect-timeout 10 --retry 5 --retry-delay 10 -L
# user-defined   Use dict "env" to create user defined environvent variables: key is name of new variable, value is a command that generate value
#
# fields:
#   download: [<url>] uses curl by default. For wget and scripts specify an explicit command in field "download-command".
#   download-command: <command> or [<command>]
#   parser: <command> or [<command>]
#
# SORT ALPHABETICALLY
#
##### protein

BacMet:
    category: protein
    homepage: http://bacmet.biomedicine.gu.se/
    type: function annotation
    version: curl ${CURL_OPTS} "http://bacmet.biomedicine.gu.se/index.html" | grep -o  "Database Statistics (version [0-9\.]*)" | grep -o [0-9\.]*
    download: http://bacmet.biomedicine.gu.se/download/BacMet1.1.zip
    parser:
      - unzip -o ${SOURCE_DIR}/BacMet1.1.zip -d ${SOURCE_DIR}
      - ${M5NR_BIN}/bacmet.pl ${SOURCE_DIR}/BacMet_EXP.704.fasta ${SOURCE_DIR}/BacMet_PRE.*.fasta
      - sort -T . -u md52seq.txt > md52seq.txt.sort
      - mv md52seq.txt.sort md52seq.txt

CARD:
    category: protein
    homepage: https://card.mcmaster.ca
    type: function annotation
    version: curl ${CURL_OPTS} "https://card.mcmaster.ca/download" | grep ">CARD<" | grep -o ">[0-9][0-9\.]*<" | head -n1 |  grep -o "[0-9\.]*"
    download: https://card.mcmaster.ca/latest/data
    parser:
      - tar -xjf ${SOURCE_DIR}/data -C ${SOURCE_DIR}
      # note, file name 'ncbi_taxomony.csv' is misspelled in tarball, may have name changed in future
      - ${M5NR_BIN}/card.pl ${SOURCE_DIR}/protein_fasta_protein_homolog_model.fasta ${SOURCE_DIR}/ncbi_taxomony.csv
      - ${M5NR_BIN}/obo2hierarchy.pl ${SOURCE_DIR}/aro.obo
      - sort -T . -u md52seq.txt > md52seq.txt.sort
      - mv md52seq.txt.sort md52seq.txt

CAZy:
    category: protein
    type: hierarchical function annotation
    depth: 2
    homepage: http://www.cazy.org
    no-download: true
    depends:
      - TrEmble
      - Swiss-Prot
    parser:
      - cp ../TrEmble/md52id_cazy.txt md52id.txt
      - cat ../Swiss-Prot/md52id_cazy.txt >> md52id.txt
      - ${M5NR_BIN}/create-cazy-hierarchy.pl --input md52id.txt > id2hierarchy.txt
    # the hierarchy is hardcoded in script

COG:
    category: protein
    type: hierarchical function annotation
    depth: 3
    version: echo '-'
    depends:
      - Swiss-Prot
      - TrEmble
    download:
      - http://eggnogdb.embl.de/download/eggnog_4.5/data/NOG/NOG.annotations.tsv.gz
    parser:
      - cp ../TrEmble/md52id_cog.txt md52id.txt
      - cat ../Swiss-Prot/md52id_cog.txt >> md52id.txt
      - zcat ${SOURCE_DIR}/NOG.annotations.tsv.gz | cut -f2,5,6 | fgrep COG > ${SOURCE_DIR}/id_mapper.txt
      - ${M5NR_BIN}/create-nog-hierarchy.pl --input ${SOURCE_DIR}/id_mapper.txt > id2hierarchy.txt
      - cut -f1,4 id2hierarchy.txt > id2func.txt
    # the hierarchy is hardcoded in script

EC:
    category: protein
    type: hierarchical function annotation
    depth: 4
    homepage: https://enzyme.expasy.org
    version: curl ${CURL_OPTS} "ftp://ftp.expasy.org/databases/enzyme/release/enzclass.txt" | grep '^Release' | grep -o '[0-9a-zA-Z\-]\+$'
    download:
      - ftp://ftp.expasy.org/databases/enzyme/enzyme.dat
      - ftp://ftp.expasy.org/databases/enzyme/enzclass.txt
    depends:
      - Swiss-Prot
      - TrEmble
    parser:
      - cp ../TrEmble/md52id_ec.txt md52id.txt
      - cat ../Swiss-Prot/md52id_ec.txt >> md52id.txt
      - ${M5NR_BIN}/create-ec-hierarchy.pl --class ${SOURCE_DIR}/enzclass.txt --input ${SOURCE_DIR}/enzyme.dat > id2hierarchy.txt
      - cut -f1,5 id2hierarchy.txt > id2func.txt

EggNOG:
    category: protein
    type: hierarchical function annotation
    depth: 3
    homepage: http://eggnogdb.embl.de
    version: curl ${CURL_OPTS} "http://eggnogdb.embl.de/download/" | grep -o "eggnog_[0-9\.]*" | cut -d "_" -f 2 | sort -u  --version-sort  | tail -n1
    depends:
      - Swiss-Prot
      - TrEmble
    download:
      - http://eggnogdb.embl.de/download/eggnog_4.5/data/NOG/NOG.annotations.tsv.gz
    parser:
      - cp ../TrEmble/md52id_eggnog.txt md52id.txt
      - cat ../Swiss-Prot/md52id_eggnog.txt >> md52id.txt
      - zcat ${SOURCE_DIR}/NOG.annotations.tsv.gz | cut -f2,5,6 | fgrep ENOG > ${SOURCE_DIR}/id_mapper.txt
      - ${M5NR_BIN}/create-nog-hierarchy.pl --input ${SOURCE_DIR}/id_mapper.txt > id2hierarchy.txt
      - cut -f1,4 id2hierarchy.txt > id2func.txt
    # the hierarchy is hardcoded in script

GenBank:
    category: protein
    type: function annotation
    download:
      - ftp://ftp.ncbi.nih.gov/blast/db/FASTA/nr.gz
    version: date --date=$(wget -qO- ftp.ncbi.nih.gov/blast/db/FASTA/ | grep ">nr.gz<" | grep -o "[0-9\-]\{10\}") '+%Y-%m-%d'
    parser:
      - ${M5NR_BIN}/genbank.pl ${SOURCE_DIR}/nr.gz
      - sort -T . -u md52seq.txt > md52seq.txt.sort
      - mv md52seq.txt.sort md52seq.txt

goslim:
    category: protein
    type: hierarchical function annotation
    depth: 3
    homepage: http://www.geneontology.org
    version: curl ${CURL_OPTS} "http://archive.geneontology.org/full/DATESTAMP"
    depends:
      - Swiss-Prot
      - TrEmble
    download:
      - http://www.geneontology.org/ontology/subsets/goslim_metagenomics.obo
    parser:
      - cp ../TrEmble/md52id_go.txt md52id.txt
      - cat ../Swiss-Prot/md52id_go.txt >> md52id.txt
      - ${M5NR_BIN}/goslim.pl ${SOURCE_DIR}/goslim_metagenomics.obo
      - cut -f1,4 id2hierarchy.txt > id2func.txt

Greengenes:
    category: rna
    type: SSU
    homepage: http://greengenes.lbl.gov/
    version: date --date="$(curl ${CURL_OPTS} http://greengenes.lbl.gov/Download/Sequence_Data/Fasta_data_files/ | grep current_GREENGENES_gg16S_unaligned.fasta.gz | grep -o "[0-9][0-9]-.*-[0-9][0-9][0-9][0-9]")" '+%Y-%m-%d'
    download:
      - http://greengenes.lbl.gov/Download/Sequence_Data/Fasta_data_files/current_GREENGENES_gg16S_unaligned.fasta.gz
    parser:
      - ${M5NR_BIN}/greengenes.pl ${SOURCE_DIR}/current_GREENGENES_gg16S_unaligned.fasta.gz
      - sort -T . -u md52rnaseq.txt > md52rnaseq.txt.sort
      - mv md52rnaseq.txt.sort md52rnaseq.txt

InterPro:
    category: protein
    type: function annotation
    version: curl ${CURL_OPTS} ftp://ftp.ebi.ac.uk/pub/databases/interpro/current/release_notes.txt | grep "Release [0-9]" | grep -o "[0-9]*\.[0-9]*"
    depends:
      - Swiss-Prot
      - TrEmble
    download:
      - ftp://ftp.ebi.ac.uk/pub/databases/interpro/${VERSION}/names.dat
    parser:
      - cp ../TrEmble/md52id_ipr.txt md52id.txt
      - cat ../Swiss-Prot/md52id_ipr.txt >> md52id.txt
      - cp ${SOURCE_DIR}/names.dat id2func.txt

KEGG:
    category: protein
    type: hierarchical function annotation
    homepage: http://www.genome.jp/kegg/
    depth: 4
    no-download: true
    depends:
      - Swiss-Prot
      - TrEmble
    parser:
      - cp ../TrEmble/md52id_kegg.txt md52id.txt
      - cat ../Swiss-Prot/md52id_kegg.txt >> md52id.txt
    comment: kegg EC and KO mappings obtained from UniProt, KEGG maps from KEGG
    comment2: KO hierarchy from ???

#unique_func.txt
M5functions:
    category: function
    type: protein
    no-download: true
    depends:
      - BacMet
      - CARD
      - CAZy
      - COG
      - EC
      - EggNOG
      - GenBank
      - goslim
      - InterPro
      - KEGG
      - PATRIC
      - PFAM
      - PhAnToMe
      - RefSeq
      - SEED-Annotations
      - SEED-Subsystems
#     - singlecopygenes
      - Swiss-Prot
      - TrEmble
    parser:
      - cat ../*/md52func.txt ../*/id2func.txt | cut -f2 | sort -T . -u -o unique_func.txt

#M5nr.fasta
M5nr:
    category: fasta
    type: protein
    no-download: true
    depends:
      - BacMet
      - CARD
      - CAZy
      - COG
      - EC
      - EggNOG
      - GenBank
      - goslim
      - InterPro
      - KEGG
      - PATRIC
      - PFAM
      - PhAnToMe
      - RefSeq
      - SEED-Annotations
      - SEED-Subsystems
#     - singlecopygenes
      - Swiss-Prot
      - TrEmble
    parser:
      - sort -T . -m -u ../*/md52seq.txt | ${M5NR_BIN}/tab2fasta.pl > m5nr.fasta

#M5rna.fasta
M5rna:
    category: fasta
    type: rna
    no-download: true
    depends:
      - SILVA-SSU
      - SILVA-LSU
      - RDP
      - Greengenes
    parser:
      - sort -T . -m -u ../*/md52rnaseq.txt | ${M5NR_BIN}/tab2fasta.pl > m5rna.fasta

# MOTUDB a set of 40 protein-coding phylogenetic marker genes (MGs) have been identified (Ciccarelli et al SCience 2006)
motuDB:
    category: protein
    type: filter set
    homepage: http://www.bork.embl.de/software/mOTU/
    version: curl ${CURL_OPTS} http://vm-lux.embl.de/~kultima/MOCAT/download.html | grep -o "mOTU\.v[0-9\.] " | grep -o "v[0-9\.]" | grep -o "[0-9\.]"
    download:
      - http://vm-lux.embl.de/~kultima/share/mOTU/mOTU.v${VERSION}.padded.tar.gz
    parser:
      - tar -xzf ${SOURCE_DIR}/mOTU.v${VERSION}.padded.tar.gz -C ${SOURCE_DIR}
      - ${M5NR_BIN}/motudb.pl ${SOURCE_DIR}/mOTU.v${VERSION}.padded
      - sort -T . -u md52seq.txt > md52seq.txt.sort
      - mv md52seq.txt.sort md52seq.txt

NCBI-Taxonomy:
    category: taxonomy
    type: hierarchical organism annotation
    homepage: https://www.ncbi.nlm.nih.gov/taxonomy
    version: echo ${TODAY}
    download:
      - ftp://ftp.ebi.ac.uk/pub/databases/taxonomy/taxonomy.dat
    parser:
      - ${M5NR_BIN}/parse_taxonomy.py --input ${SOURCE_DIR}/taxonomy.dat --output ${SOURCE_DIR}/taxonomy.json
      - ${M5NR_BIN}/clean_taxonomy.py --header --rank --format tsv --input ${SOURCE_DIR}/taxonomy.json --output id2hierachy.txt

PATRIC:
    category: protein
    type: function annotation
    homepage: https://www.patricbrc.org/
    version: wget -qO- ftp://ftp.patricbrc.org/patric2/ | grep current_release | grep -o "20[0-9][0-9] [a-zA-Z]*"
    download-command: ${M5NR_BIN}/download_PATRIC.sh
    parser:
      - ${M5NR_BIN}/patric.pl ${SOURCE_DIR}/
      - sort -T . -u md52seq.txt > md52seq.txt.sort
      - mv md52seq.txt.sort md52seq.txt

PFAM:
    category: protein
    type: function annotation
    homepage: http://pfam.xfam.org/
    version: curl ${CURL_OPTS} 'ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/relnotes.txt' | head -n 5 | grep -o 'RELEASE [0-9\.]\+' | cut -f2 -d' '
    download:
      - ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.clans.tsv.gz
    depends:
      - Swiss-Prot
      - TrEmble
    parser:
      - cp ../TrEmble/md52id_pfam.txt md52id.txt
      - cat ../Swiss-Prot/md52id_pfam.txt >> md52id.txt
      - zcat ${SOURCE_DIR}/Pfam-A.clans.tsv.gz | cut -f1,5 > id2func.txt

PhAnToMe:
    category: protein
    type: function annotation
    homepage: http://www.phantome.org
    env:
        TIMESTAMP: curl -s http://www.phantome.org/Downloads/proteins/all_sequences/ | grep -o ">phage_proteins_[0-9]*.fasta.gz" | sort | tail -n 1 | grep -o "[0-9]*"
    version: date -d @${TIMESTAMP} +"%Y%m%d"
    download:
      - http://www.phantome.org/Downloads/proteins/all_sequences/phage_proteins_${TIMESTAMP}.fasta.gz
    comment: curl ${CURL_OPTS} "http://shock.metagenomics.anl.gov/node?query&type=data-library&project=M5NR&data-library-name=M5NR_source_Phantome&version=${VERSION}" | grep -o "[0-f]\{8\}-[0-f]\{4\}-[0-f]\{4\}-[0-f]\{4\}-[0-f]\{12\}"`
    parser:
      - ${M5NR_BIN}/phantome.pl ${SOURCE_DIR}/phage_proteins_${TIMESTAMP}.fasta.gz
      - sort -T . -u md52seq.txt > md52seq.txt.sort
      - mv md52seq.txt.sort md52seq.txt

RDP:
    category: rna
    type:
      - SSU
      - LSU
      - ITS
    homepage: http://rdp.cme.msu.edu
    version: curl ${CURL_OPTS} 'http://rdp.cme.msu.edu/download/releaseREADME.txt'
    download:
      - http://rdp.cme.msu.edu/download/current_Bacteria_unaligned.gb.gz
      - http://rdp.cme.msu.edu/download/current_Archaea_unaligned.gb.gz
      - http://rdp.cme.msu.edu/download/current_Fungi_unaligned.gb.gz
    parser:
      - ${M5NR_BIN}/rdp.pl ${SOURCE_DIR}/current_Fungi_unaligned.gb.gz ${SOURCE_DIR}/current_Bacteria_unaligned.gb.gz ${SOURCE_DIR}/current_Archaea_unaligned.gb.gz
      - sort -T . -u md52rnaseq.txt > md52rnaseq.txt.sort
      - mv md52rnaseq.txt.sort md52rnaseq.txt

RefSeq:
    category: protein
    type: function annotation
    version: curl ${CURL_OPTS} ftp://ftp.ncbi.nih.gov/refseq/release/RELEASE_NUMBER
    env:
        COUNT: curl -s ftp://ftp.ncbi.nih.gov/refseq/release/complete/ | grep -o "complete.nonredundant_protein.*\.faa\.gz" | sort -V | tail -n 1 | grep -o [0-9]*
    download: ftp://ftp.ncbi.nih.gov/refseq/release/complete/complete.nonredundant_protein.{1..${COUNT}}.protein.gpff.gz
    resume-download: true
    parser:
      - ${M5NR_BIN}/refseq.pl ${SOURCE_DIR}
      - sort -T . -u md52seq.txt > md52seq.txt.sort
      - mv md52seq.txt.sort md52seq.txt

SEED-Annotations:
    category: protein
    type: function annotation
    homepage: http://www.theseed.org
    version: echo ${TODAY}
    download-command: ${M5NR_BIN}/querySAS.pl --source=SEED  --output=SEED.md52id2func2org
    resume-download: true
    parser:
      - ${M5NR_BIN}/seed-annotations.pl ${SOURCE_DIR}/SEED.md52id2func2org
      - sort -T . -u md52seq.txt > md52seq.txt.sort
      - mv md52seq.txt.sort md52seq.txt

SEED-Subsystems:
    category: protein
    type: hierarchical function annotation
    depth: 4
    homepage: http://www.theseed.org
    version: echo ${TODAY}
    download-command: ${M5NR_BIN}/querySAS.pl --source=Subsystems --output=Subsystems.subsystem2role2seq --verbose
    resume-download: true
    parser:
      - ${M5NR_BIN}/subsystems.pl ${SOURCE_DIR}
      - cut -f1,5 id2hierarchy.txt > id2func.txt
      - sort -T . -u md52seq.txt > md52seq.txt.sort
      - mv md52seq.txt.sort md52seq.txt

# no suitable download mechanism other than manual, does not seem to be updated
#FOAM:
#    category: protein
#    homepage: http://cbb.pnnl.gov/portal/software/FOAM.html
#    type: hierarchical function annotation
#    download:
#      - http://cbb.pnnl.gov/portal/software/FOAM.html

# not enabeled for now
#singlecopygenes:
#    category: protein
#    type: filter set
#    comment: From Will

SILVA-LSU:
    category: rna
    type: LSU
    homepage: http://www.arb-silva.de
    version: curl ${CURL_OPTS} -N "ftp://ftp.arb-silva.de//current/Exports/README.txt" | head -n 1 | grep -o "SILVA [0-9.]*" | cut -d ' ' -f 2
    download:
      - ftp://ftp.arb-silva.de/current/Exports/SILVA_${VERSION}_LSURef_tax_silva_trunc.fasta.gz
    parser:
      - ${M5NR_BIN}/silva.pl ${SOURCE_DIR}/SILVA_${VERSION}_LSURef_tax_silva_trunc.fasta.gz
      - sort -T . -u md52rnaseq.txt > md52rnaseq.txt.sort
      - mv md52rnaseq.txt.sort md52rnaseq.txt

SILVA-SSU:
    category: rna
    type: SSU
    homepage: http://www.arb-silva.de
    version: curl ${CURL_OPTS} -N "ftp://ftp.arb-silva.de//current/Exports/README.txt" | head -n 1 | grep -o "SILVA [0-9.]*" | cut -d ' ' -f 2
    download:
      - ftp://ftp.arb-silva.de/current/Exports/SILVA_${VERSION}_SSURef_tax_silva_trunc.fasta.gz
    parser:
      - ${M5NR_BIN}/silva.pl ${SOURCE_DIR}/SILVA_${VERSION}_SSURef_tax_silva_trunc.fasta.gz
      - sort -T . -u md52rnaseq.txt > md52rnaseq.txt.sort
      - mv md52rnaseq.txt.sort md52rnaseq.txt

Swiss-Prot:
    category: protein
    type: function annotation
    download:
      - ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.dat.gz
    version: curl ${CURL_OPTS} ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/reldate.txt | grep "Swiss-Prot" | grep -o "Release 20[0-9_]*" | grep -o "20[0-9_]*"
    parser:
      - ${M5NR_BIN}/uniprot.pl ${SOURCE_DIR}/uniprot_sprot.dat.gz
      - sort -T . -u md52seq.txt > md52seq.txt.sort
      - mv md52seq.txt.sort md52seq.txt

TrEmble:
    category: protein
    type: function annotation
    download:
      - ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_trembl.dat.gz
    version: curl ${CURL_OPTS} ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/reldate.txt | grep "TrEMBL" | grep -o "Release 20[0-9_]*" | grep -o "20[0-9_]*"
    parser:
      - ${M5NR_BIN}/uniprot.pl ${SOURCE_DIR}/uniprot_trembl.dat.gz
      - sort -T . -u md52seq.txt > md52seq.txt.sort
      - mv md52seq.txt.sort md52seq.txt
