
# protein

Uniprot:
  category: protein
  type: Functional annotation
  download:
    - ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/{reldate.txt, uniprot_sprot.dat.gz, uniprot_trembl.dat.gz}
  version: head -n1 reldate.txt | grep -o "[0-9]\{4\}_[0-9]*"
  version_lastest: curl --silent ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/reldate.txt | head -n1 | grep -o "[0-9]\{4\}_[0-9]*"
Swissprot:
  category: protein
  type: Functional annotation
  download:
    - ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_trembl.dat.gz
TrEmble:
  category: protein
  type: Functional annotation
  download:
    - ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.dat.gz 
PIR:
  category: protein
  type: Functional annotation
Interpro:
  category: protein
  type: Hierarchical functional annotation
  download:
    - null
#    - ftp://ftp.ebi.ac.uk/pub/databases/interpro/Current/
IMG:
  category: protein
  type: Functional annotation
  download:
    - ftp://ftp.jgi-psf.org/pub/IMG/img_core_v400.tar 
PFAM:
  type: Hierarchical functional annotation?
  download: 
      -null
      # comes from Uniprot
Genbank:
  category: protein
  type: Functional annotation
  download:
    - ftp://ftp.ncbi.nih.gov/blast/db/FASTA/*
RefSeq:
  category: protein
  type: Functional annotation
  download:
    - ftp://ftp.ncbi.nih.gov/refseq/release/complete/*.genomic.gbff.gz
SEED-Subsystems:
  category: protein
  type: Hierarchical functional annotation
  homepage: http://www.theseed.org
  download:
      - null
  comment: <special downloader>
SEED-Annotations:
  category: protein
  homepage: http://www.theseed.org
  type: Functional annotation
  comment: <special downloader>
Cazy:
  category: protein
  homepage: http://www.cazy.org
  type: Hierarchical functional annotation
  download:
    - www.cazy.org bin/get_cazy_table.pl
FungiDB:
  category: protein
  homepage: http://fungalgenomes.org
  download:
    - http://fungalgenomes.org/public/mobedac/for_VAMPS/fungalITSdatabaseID.taxonomy.seqs.gz

COG:
  category: protein
  type: Hierarchical functional annotation
  download:
    - null
#    - ftp://ftp.ncbi.nih.gov/pub/COG/COG2014/data/ 
#    obtained via Eggnog v4.5
Kegg:
  category: protein
  homepage: http://www.genome.jp/kegg/
  type: Hierarchical functional annotation
  download: 
    - null
  # kegg EC and KO mappings obtained from UniProt, KEGG maps from KEGG
  # EC hierarchy from elsewhere    
NOG:
  category: protein
  type: Hierarchical functional annotation
  homepage: http://eggnogdb.embl.de
  download:
    - http://eggnogdb.embl.de/download/eggnog_4.5/eggnog4.proteins.core_periphery.fa.gz
  comment: https://github.com/jhcepas/eggnog-mapper/blob/master/eggnogmapper/common.py
CARD:
  category: protein
  homepage: https://card.mcmaster.ca
  type: Functional annotation
  download:
    - https://card.mcmaster.ca/latest/data
BacMet:
  category: protein
  homepage: http://bacmet.biomedicine.gu.se/
  type: Functional annotation
  download:
    - http://bacmet.biomedicine.gu.se/download/BacMet1.1.zip
ACLAME:
  category: protein
  homepage: http://aclame.ulb.ac.be/
  type: Functional annotation
  download:
    - http://aclame.ulb.ac.be/perl/Aclame/Tools/exporter.cgi?id=all&source=proteins&entry_id=1&length=on&ncbi_desc=on&family=on&xrefs=on&mge_id=on&mge_name=on&funct=on&sequence=on&fmt=fasta&format=gzip&x=85&y=15&notify=1
    - http://aclame.ulb.ac.be/perl/Aclame/Tools/exporter.cgi?source=families&id=all&fam_id=on&aclame_fct=on&aclame_fct_name=on&aclame_fct_desc=on&nb_prot=on&x=112&y=11&mge_name=on&host_id=on&host_name=on&format=gzip&notify=1

ARDB:
  category: protein
  homepage: https://ardb.cbcb.umd.edu/
  type: Functional annotation
  download:
    - ftp://ftp.cbcb.umd.edu/pub/data/ARDB/ARDBflatFiles.tar.gz
PhAnToMe:
  category: protein
  homepage: http://www.phantome.org
  type: Functional annotation
  download:
    - http://www.phantome.org/Downloads/proteins/all_sequences/
goslim:
  category: protein
  homepage: http://www.geneontology.org
  type: Hierarchical functional annotation
  download:
    - http://www.geneontology.org/ontology/subsets/goslim_metagenomics.obo
#bactNOG:
 # category: protein
#  type: Hierarchical functional annotation
#  comment: Mapped from eggnog
#arNOG:
#  category: protein
#  type: Hierarchical functional annotation
#  comment: Mapped from eggnog
HITdb:
  category: protein
  homepage: https://github.com/microbiome/HITdb.git
  type: Functional annotation
  download:
      - https://github.com/microbiome/HITdb/archive/master.zip
  comment: reduced 16s db for human microbiome

# MOTUDB a set of 40 protein-coding phylogenetic marker genes (MGs) have been identified (Ciccarelli et al SCience 2006)
motuDB:
  category: protein
  homepage: http://www.bork.embl.de/software/mOTU/
  type: Filter set
  download: 
    - http://vm-lux.embl.de/~kultima/share/mOTU/mOTU.v1.padded.tar.gz
# no suitable download mechanism other than manual, does not seem to be updated
#FOAM:
#  category: protein
#  homepage: http://cbb.pnnl.gov/portal/software/FOAM.html
#  type: Hierarchical functional annotation
#  download: 
#    - http://cbb.pnnl.gov/portal/software/FOAM.html
singlecopygenes:
  category: protein
  type: Filter set
  comment: From Will
# rRNA
Silva-LSU:
  homepage: http://www.arb-silva.de
  category: rRNA
  type: SSU
  download: 
    - ftp://ftp.arb-silva.de/current/Exports/rast
Silva-SSU:
  homepage: http://www.arb-silva.de
  category: rRNA
  type: LSU
  download:
      - null
Greengenes:
  homepage: http://greengenes.lbl.gov/
  category: rRNA
  type: SSU?
  download: 
    - http://greengenes.lbl.gov/Download/Sequence_Data/Fasta_data_files/current_GREENGENES_gg16S_unaligned.fasta.gz
FungiDB:
  category: rRNA
  homepage: http://fungalgenomes.org/
  type: ITS
  download: 
    - http://fungalgenomes.org/public/mobedac/for_VAMPS/fungalITSdatabaseID.taxonomy.seqs.gz
RDP:
  category: rRNA
  homepage: http://rdp.cme.msu.edu
  type: SSU
  download:
    - http://rdp.cme.msu.edu/download/releaseREADME.txt'
    - http://rdp.cme.msu.edu/download/current_Bacteria_unaligned.gb.gz
    - http://rdp.cme.msu.edu/download/current_Archaea_unaligned.gb.gz
    - http://rdp.cme.msu.edu/download/current_Fungi_unaligned.gb.gz
MITOZOA:
  category: rRNA
  homepage: http://srv00.recas.ba.infn.it/mitozoa
  type: mtRNA
  download:
    - http://srv00.recas.ba.infn.it/mitozoa/ftp/dbMZ_v10.0.zip



