#
# docker build -t mgrast/m5nr-upload -f upload/Dockerfile-upload .
# docker run -i -d \
#        --name m5nr-upload \
#        -v $DIR/m5nr/:/m5nr_data/ \
#        -v $DIR/docker:/docker/ \
#        -v /var/run/docker.sock:/var/run/docker.sock
#        mgrast/m5nr-upload bash
#
# export M5NR_VERSION=12
# export DOCKERVERSION=`/usr/bin/docker --version | grep -o '[0-9]*\.[0-9]*\.[0-9][a-z-]*'`
# export SOLR_URL="http://140.221.76.69:8983/solr"
#
### to upload files to shock ###
# docker exec m5nr-upload m5nr_master.sh -a upload -v $M5NR_VERSION -t $TOKEN
### to load solr m5nr data ###
# docker exec m5nr-upload docker_setup.sh $DOCKERVERSION
# docker exec m5nr-upload solr_load.sh -n -i $INPUT_URI -v $M5NR_VERSION -s $SOLR_URL
### to load cassandra m5nr data ###
# docker exec m5nr-upload cassandra_load.py -n -i $INPUT_URI -v $M5NR_VERSION -t $TOKEN
#

FROM FROM ubuntu:16.04

RUN apt-get update && apt-get install -y \
  git-core \
  vim \
  curl \
  python-pip \
  python-yaml

RUN add-apt-repository ppa:openjdk-r/ppa && \
    apt-get update && \
    apt-get install -y openjdk-8-jdk maven

# python dependencies
RUN pip2 install --upgrade pip
RUN python -m pip install requests_toolbelt

### install solr-import-export-json
RUN cd / \
    && git clone https://github.com/freedev/solr-import-export-json.git \
    && cd solr-import-export-json \
    && mvn clean package

### install yq
RUN curl -L "https://github.com/mikefarah/yq/releases/download/1.14.0/yq_linux_amd64" > /usr/bin/yq \
    && chmod +x /usr/bin/yq

# copy myM5NR and set up env
RUN mkdir -p /myM5NR /myM5NR/bin
COPY bin/* /myM5NR/bin/
COPY upload/bin/* /myM5NR/bin/
COPY config/upload.yaml /myM5NR/
COPY upload/schema/* /myM5NR/schema/
ENV PATH $PATH:/myM5NR/bin

RUN mkdir -p /m5nr_data
WORKDIR /m5nr_data
